development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://wbfpshghlkkcyw:k7FdcoRtwPZFPXLB6tBnOdpBJS@ec2-54-225-195-254.compute-1.amazonaws.com:5432/d7l821166bofs7
